/** Portfolio-safe display names (no employer-specific terminology). */

export const LEX = {
  appTitle: "Relay Pulse",
  companyName: "Relay Logistics",
  companyBlurb: "Fictional delivery network — all metrics are simulated.",
  appSubtitle: "Sign in to access the analytics workspace",
  warehouseSignIn: "Connect to warehouse",
  warehouseSigningIn: "Connecting…",
  warehouseTitle: "Establish the warehouse session to refresh metrics",
  warehouseRefreshHint: "Force a full warehouse refresh of cached metrics",
  warehouseRefreshNote: "A warehouse sign-in step may run if no session is active.",

  tabRegion: "Network",
  tabMarket: "Market",
  tabSla: "SLA breaches",
  tabQueue: "Queue aging",
  tabRedispatch: "Redispatch",
  tabAccept: "Accept latency",
  tabLogs: "Logs",

  demoDisclaimer: "Relay Logistics demo · all figures are simulated for portfolio use.",

  metrics: {
    totalOrders: "Completed jobs",
    slaBreach: "SLA breach share",
    slaBreachShort: "Breach %",
    queueAging: "Queue aging share",
    queueAgingShort: "Aging %",
    oversizeABreach: "Tier A breach share",
    oversizeAShort: "Tier A %",
    oversizeBBreach: "Tier B breach share",
    oversizeBShort: "Tier B %",
    redispatch: "Redispatch share",
    redispatchShort: "Redispatch %",
    cycleTime: "Mean cycle time",
    cycleTimeShort: "Cycle",
    acceptLatency: "Mean accept latency",
    acceptLatencyShort: "Accept",
    acceptLatencySec: "Accept (s)",
    breachCount: "SLA breach count",
    breachRate: "Breach rate",
    agingCount: "Queue aging count",
    agingRate: "Aging rate",
    officialBreach: "Audited breach count",
    reasonHeading: "Root-cause signals (multi-tag)",
    slaTrend: "SLA breach trend",
    agingTrend: "Queue aging trend",
    oversizeA: "Tier A (oversize)",
    oversizeB: "Tier B (oversize)",
    oversizeBoth: "Tier A | B",
    partner: "Partner",
    fieldUnit: "Field unit",
  },
} as const;
